server {
  listen 80;

  location = / {
    return 200 "Day 5 Nginx reverse proxy is running. Try /blue, /green, or /health.\n";
    add_header Content-Type text/plain;
  }

  location /blue {
    proxy_pass http://app-blue:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /green {
    proxy_pass http://app-green:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /health {
    proxy_pass http://app-blue:3000/health;
    proxy_set_header Host $host;
  }
}
